// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import { TextTransformProperty, TextDecorationProperty } from "csstype";
export interface TextStyle {
  fontFamily: string;
  fontSize: string;
  fontWeight: number;
  fontStyle: string;
  lineHeight?: string;
  letterSpacing: string;
  textDecoration: TextDecorationProperty<string | number>;
  textTransform: TextTransformProperty;
}
export const button: TextStyle;
export const buttonSmall: TextStyle;
export const code: TextStyle;
export const h1: TextStyle;
export const h2: TextStyle;
export const h3: TextStyle;
export const h4: TextStyle;
export const h5: TextStyle;
export const h6: TextStyle;
export const link: TextStyle;
export const linkSmall: TextStyle;
export const paragraph: TextStyle;
export const paragraphLarge: TextStyle;
export const paragraphSmall: TextStyle;
