// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const dimensions: {
  sizeMedium: string;
  sizeSmall: string;
  sizeXlarge: string;
};
export const radius: {
  radiusLarge: string;
  radiusMedium: string;
  radiusPill: string;
  radiusSmall: string;
};
export const spacing: {
  paddingLarge: string;
  paddingMedium: string;
  paddingSmall: string;
  spaceMedium: string;
  spaceSmall: string;
  spacingLarge: string;
};
