// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const elevation1: string;
export const elevation2: string;
export const elevation3: string;
export const elevation4: string;
export const focusDanger: string;
export const focusPrimary: string;
export const focusSecondary: string;
