// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const elevation1 = "0px 1px 2px 0px rgba(0,0,0,0.08)";
export const elevation2 = "0px 2px 4px 0px rgba(0,0,0,0.12)";
export const elevation3 = "0px 4px 8px 1px rgba(0,0,0,0.16)";
export const elevation4 = "0px 8px 16px 2px rgba(0,0,0,0.2)";
export const focusDanger = "0px 0px 0px 2px rgba(221,43,56,0.25)";
export const focusPrimary = "0px 0px 0px 2px rgba(204,224,255,1)";
export const focusSecondary = "0px 0px 0px 2px rgba(233,217,251,1)";
