// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import React, { useRef } from "react";
import { combineRef, renderChildren } from "./_internal_utils";
import { usePrimitive } from "./_internal_usePrimitive";
import { Popover } from "./builtins/Popover";
export function PopoverRoot(props) {
  const ref = useRef(null);
  const { testId, vislyProps, style, values } = usePrimitive({
    ref,
    props,
  });
  const Content = (
    <div
      ref={combineRef(props.measureRef, ref)}
      data-testid={testId}
      {...vislyProps}
      style={style}
    >
      {renderChildren(props.children, values)}
    </div>
  );

  if (props.renderInline) {
    return <>{Content}</>;
  }

  return <Popover {...props}>{Content}</Popover>;
}
