// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { RootPrimitive, TextPrimitive } from "./_internal_primitives";

const styles = [
  {
    type: "default",
    layers: {
      PyKkfRZME8: {
        none: {
          text: "This is a simple card component",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const TextContext = createContext(null);

function Text(_props) {
  const defaults = useContext(TextContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="PEk2BsMFCm"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "PEk2BsMFCm",
        scope: "LGdUUsFB7L",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <TextPrimitive
          id={"Text_PyKkfRZME8"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_LGdUUsFB7L_PyKkfRZME8"
          }
          key={"PyKkfRZME8"}
          text={
            exists(props.text) ? props.text : getStyle("PyKkfRZME8", "text")
          }
          element={getStyle("PyKkfRZME8", "htmlElement")}
        />
      )}
    </RootPrimitive>
  );
}

Text.__variants = [];

export default Text;
