// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { TextPrimitive } from "./_internal_primitives";
import { ListboxItemPrimitive } from "./_internal_listbox";

const styles = [
  {
    type: "default",
    layers: {
      "3VJGRE8vAZ": {
        none: {
          text: "List item",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "selected",
    layers: {},
  },
  {
    type: "boolean",
    propName: "small",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "selected",
    layers: {},
  },
  {
    type: "boolean",
    propName: "small",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "selected",
  },
  {
    type: "boolean",
    propName: "small",
  },
];

export const ItemContext = createContext(null);

function Item(_props) {
  const defaults = useContext(ItemContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <ListboxItemPrimitive
      {...props}
      key="listbox-item-root"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "listbox-item-root",
        scope: "BPKn9HiVM5",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <TextPrimitive
          id={"text_3VJGRE8vAZ"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_BPKn9HiVM5_3VJGRE8vAZ"
          }
          key={"3VJGRE8vAZ"}
          text={
            exists(props.label) ? props.label : getStyle("3VJGRE8vAZ", "text")
          }
          element={getStyle("3VJGRE8vAZ", "htmlElement")}
        />
      )}
    </ListboxItemPrimitive>
  );
}

Item.__variants = [
  {
    name: "selected",
    type: "variant",
  },
  {
    name: "small",
    type: "variant",
  },
];

export default Item;
