// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  SpacerPrimitive,
  TextPrimitive,
  IconPrimitive,
} from "./_internal_primitives";
import {
  SelectRoot,
  SelectOptionContainer,
  SelectButton,
} from "./_internal_select";
import * as icons from "./icons";

const styles = [
  {
    type: "default",
    layers: {
      "select-button-text": {
        none: {
          text: "Selected option",
        },
      },
      "2pmEsZq6Nc": {
        none: {
          icon: icons.vislySelect,
          useMask: true,
        },
        disabled: {
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const SelectContext = createContext(null);

function Select(_props) {
  const defaults = useContext(SelectContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <SelectRoot
      {...props}
      key="select-root"
      internal={{
        styles,
        projectId: "7X7HTLRqyD",
        layerId: "select-root",
        scope: "9cCvR1MveE",
        activeVariants,
      }}
      vislyChildren={(getStyle) => (
        <>
          <SelectButton
            key="select-button"
            id={"Button_select-button"}
            className="__visly_reset_7X7HTLRqyD __visly_scope_9cCvR1MveE_select-button"
          >
            <TextPrimitive
              id={"text_select-button-text"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_9cCvR1MveE_select-button-text"
              }
              key={"select-button-text"}
              text={
                exists(props.label)
                  ? props.label
                  : getStyle("select-button-text", "text")
              }
              element={getStyle("select-button-text", "htmlElement")}
            />
            <SpacerPrimitive
              id={"Spacer_FHgCWMno5h"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_9cCvR1MveE_FHgCWMno5h"
              }
              key={"FHgCWMno5h"}
            />
            <IconPrimitive
              id={"icon_2pmEsZq6Nc"}
              className={
                "__visly_reset_7X7HTLRqyD __visly_scope_9cCvR1MveE_2pmEsZq6Nc"
              }
              key={"2pmEsZq6Nc"}
              useMask={getStyle("2pmEsZq6Nc", "useMask")}
              src={getStyle("2pmEsZq6Nc", "icon")}
            />
          </SelectButton>
          <SelectOptionContainer
            key="select-menu"
            id={"Menu_select-menu"}
            className="__visly_reset_7X7HTLRqyD __visly_scope_9cCvR1MveE_select-menu"
            innerKey="select-menu"
            addSpacing={false}
            useButtonWidth={true}
          >
            {[
              <SpacerPrimitive
                id={"Spacer_L9G8UTWXsR"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_9cCvR1MveE_L9G8UTWXsR"
                }
                key={"L9G8UTWXsR"}
              />,
              props.children,
              <SpacerPrimitive
                id={"Spacer_fmhUdXzNqw"}
                className={
                  "__visly_reset_7X7HTLRqyD __visly_scope_9cCvR1MveE_fmhUdXzNqw"
                }
                key={"fmhUdXzNqw"}
              />,
            ]}
          </SelectOptionContainer>
        </>
      )}
    >
      {props.children}
    </SelectRoot>
  );
}

Select.__variants = [];

export default Select;
