// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { TextAreaRoot } from "./_internal_textarea";

const styles = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "small",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "small",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "small",
  },
];

export const TextAreaContext = createContext(null);

function TextArea(_props) {
  const defaults = useContext(TextAreaContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <TextAreaRoot
      {...props}
      key="textarea-root"
      internal={{
        styles,
        projectId: "7X7HTLRqyD",
        layerId: "textarea-root",
        scope: "E4LCBrJ6g5",
        activeVariants,
      }}
    >
      {(getStyle) => null}
    </TextAreaRoot>
  );
}

TextArea.__variants = [
  {
    name: "small",
    type: "variant",
  },
];

export default TextArea;
