// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import component_0 from "./Welcome";
import component_1 from "./Welcome.Hint";
export const Welcome = component_0;
Welcome.Hint = component_1;
