// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "../_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "../_internal_primitives";
import * as icons from "../icons";
import { default as Button, ButtonContext } from "../Button";
import { default as Badge, BadgeContext } from "../Badge";

const styles = [
  {
    type: "default",
    layers: {
      KzaXWj4reb: {
        none: {
          text: "Welcome to Visly",
        },
      },
      Nej5L1kG3v: {
        none: {
          text:
            "You are now viewing your UI Kit components and token styles live in the Visly starter app",
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {
      QE6seWhNpT: {
        none: {
          text: "Next hint",
          icon: icons.bookmark,
          kind: "primary",
          size: "large",
          withIcon: true,
        },
      },
      "5LziuhTddJ": {
        none: {
          text: "Open Beta",
          kind: "warning",
        },
      },
    },
  },
];

const variantPropTypes = [];

export const WelcomeContext = createContext(null);

function Welcome(_props) {
  const defaults = useContext(WelcomeContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <RootPrimitive
      {...props}
      key="XseXsgxRXE"
      addSpacing={false}
      internal={{
        projectId: "7X7HTLRqyD",
        styles: styles,
        layerId: "XseXsgxRXE",
        scope: "BtsJJmA1s6",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => [
        <ContainerPrimitive
          id={"Header_Jh431cvDFH"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_Jh431cvDFH"
          }
          key={"Jh431cvDFH"}
          addSpacing={false}
          element={getStyle("Jh431cvDFH", "htmlElement")}
        >
          <TextPrimitive
            id={"Text_KzaXWj4reb"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_KzaXWj4reb"
            }
            key={"KzaXWj4reb"}
            text={getStyle("KzaXWj4reb", "text")}
            element={getStyle("KzaXWj4reb", "htmlElement")}
          />
          <ContainerPrimitive
            id={"Container_EYSqWWqxL7"}
            className={
              "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_EYSqWWqxL7"
            }
            key={"EYSqWWqxL7"}
            addSpacing={false}
            element={getStyle("EYSqWWqxL7", "htmlElement")}
          >
            {props.Badge === undefined ? (
              <Badge
                key={"5LziuhTddJ"}
                {...getCompositeDefaultProps("5LziuhTddJ")}
                id="Badge_5LziuhTddJ"
                className="__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_5LziuhTddJ"
              />
            ) : (
              <BadgeContext.Provider
                key="5LziuhTddJ-provider"
                value={{
                  key: "5LziuhTddJ",
                  id: "Badge_5LziuhTddJ",
                  className:
                    "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_5LziuhTddJ",
                  ...getCompositeDefaultProps("5LziuhTddJ"),
                }}
              >
                {props.Badge}
              </BadgeContext.Provider>
            )}
          </ContainerPrimitive>
        </ContainerPrimitive>,
        <SpacerPrimitive
          id={"Spacer_5SQ2YXCdT4"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_5SQ2YXCdT4"
          }
          key={"5SQ2YXCdT4"}
        />,
        <TextPrimitive
          id={"Text_Nej5L1kG3v"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_Nej5L1kG3v"
          }
          key={"Nej5L1kG3v"}
          text={getStyle("Nej5L1kG3v", "text")}
          element={getStyle("Nej5L1kG3v", "htmlElement")}
        />,
        <SpacerPrimitive
          id={"Spacer_8nGCs6vuH6"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_8nGCs6vuH6"
          }
          key={"8nGCs6vuH6"}
        />,
        <ContainerPrimitive
          key={"9SrL26xV5f"}
          id={"Slot_9SrL26xV5f"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_9SrL26xV5f"
          }
          addSpacing={false}
        >
          {props.children}
        </ContainerPrimitive>,
        <SpacerPrimitive
          id={"Spacer_CPfBcPYcrm"}
          className={
            "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_CPfBcPYcrm"
          }
          key={"CPfBcPYcrm"}
        />,
        props.Button === undefined ? (
          <Button
            key={"QE6seWhNpT"}
            {...getCompositeDefaultProps("QE6seWhNpT")}
            id="Button_QE6seWhNpT"
            className="__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_QE6seWhNpT"
          />
        ) : (
          <ButtonContext.Provider
            key="QE6seWhNpT-provider"
            value={{
              key: "QE6seWhNpT",
              id: "Button_QE6seWhNpT",
              className:
                "__visly_reset_7X7HTLRqyD __visly_scope_BtsJJmA1s6_QE6seWhNpT",
              ...getCompositeDefaultProps("QE6seWhNpT"),
            }}
          >
            {props.Button}
          </ButtonContext.Provider>
        ),
      ]}
    </RootPrimitive>
  );
}

Welcome.Button = Button;
Welcome.Badge = Badge;
Welcome.__variants = [];

export default Welcome;
